# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.

# Uncomment the lines below to configure your website in a second language.
[es]
  languageCode = "es-bo"  
  contentDir = "content/es"
  title = "Colectivo UMA"
#  [es.params]
#    description = "Descripcion del sitio en Castellano..."
  
[en]
  languageCode = "en-uk"
  contentDir = "content/en"
  title = "Collective UMA"
#  [en.params]
#      description = "Site description in English ..."
# Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "合作社 UMA"
#  [zh.params]
#      description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about  "
#    weight = 1
